const mongoose=require('mongoose')
const orderSchema=new mongoose.Schema({
    shippingInfo:{
        address:{   
          type:String,
          required:true
        },
        city:{
            type:String,
            required:true},
        phoneNo:{
            type:Number,
            required:true
        },
        postalCode:{
            type:Number,
            required:true
        },
        country:{
            type:String,
            required:true
        },
        state:{
            type:String,
            required:true
        }
    },
    orderItems:[
        {
            name:{
                type:String,
                required:true
            },
            quantity:{
                type:Number,
                required:true
            },
            image:{
                type:String,
                required:true
            },
            price:{
                type:Number,
                required:true
            },
            product:{
                type:mongoose.Schema.ObjectId,
                ref:'Product',
                required:true
            }
        }
    ],
    paymentInfo:{
        id:{
            type:String
        },
        status:{
            type:String
        }
    },
    itemsPrice:{
        type:Number,
        required:true,
        default:0.0
    },
    taxPrice:{
        type:Number,
        required:true,
        default:0.0
    },
    shippingPrice:{
        type:Number,
        required:true,
        default:0.0
    },
    totalPrice:{
        type:Number,
        required:true,
        default:0.0
    },
    user:{
        type:mongoose.Schema.ObjectId,
        ref:'User',
        required:true
    },
    paidAt:{
        type:Date
    },
    deliveredAt:{
        type:Date
    },
    createdAt:{
        type:Date,
        default:Date.now    
    }
})
module.exports=mongoose.model('Orde',orderSchema)


            